"""
MatGuide AI — Construction Material Guide Assistant
------------------------------------------------------
Type any construction material name and get a structured guide:
introduction, composition, properties, purpose/use, types/grades,
standards, precautions, and alternatives — generated by an LLM
through the Groq API. Also supports recent-search history,
favorites/bookmarks, a reference photo (via Wikipedia, with a
placeholder fallback), reference market rates for 3 Pakistani
cities, a unit converter, dark/light theme, WhatsApp sharing,
side-by-side material comparison, and PDF download of the guide.

Run:
    streamlit run app.py

API key:
    Set GROQ_API_KEY in .streamlit/secrets.toml (see
    .streamlit/secrets.toml.example) or as an environment variable.
    You can also paste a key directly in the sidebar for a quick local
    test — it is only kept in memory for this session, never saved
    to disk or committed anywhere.

Note on History / Favorites:
    These are kept in the browser session only (st.session_state).
    They reset if you refresh the page or close the tab — this app
    has no database, so nothing is saved permanently across visits.

Note on Live Rates:
    There is no free, public, real-time API for construction material
    prices in Pakistan. RATES below is a manually-maintained reference
    table (not a live feed) — update the numbers here whenever you
    have newer data. Current values are sourced from Pakistan Bureau
    of Statistics city-level CPI data (Jan 2026) via a news report,
    reflected as of this app's last code update.
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime
from urllib.parse import quote, quote_plus

import requests
import streamlit as st

# ----------------------------------------------------------------------
# Page config
# ----------------------------------------------------------------------
st.set_page_config(page_title="MatGuide AI", page_icon="🧱", layout="centered")

if "dark_mode" not in st.session_state:
    st.session_state.dark_mode = False

PRIMARY = "#4FA8E0" if st.session_state.dark_mode else "#1F4E79"

if st.session_state.dark_mode:
    BG, CARD_BG, CARD_BORDER, TEXT, SUBTEXT = "#0E1117", "#1B1F27", "#333A45", "#F0F2F6", "#9CA3AF"
    RATE_BG, RATE_BORDER = "#132A3E", "#234158"
else:
    BG, CARD_BG, CARD_BORDER, TEXT, SUBTEXT = "#FFFFFF", "#FFFFFF", "#E5E7EB", "#1A1A1A", "#6B7280"
    RATE_BG, RATE_BORDER = "#F0F6FB", "#D6E4F0"

st.markdown(
    f"""
    <style>
    .stApp {{ background-color:{BG}; }}
    .app-header {{ font-size:1.8rem; font-weight:800; color:{PRIMARY}; margin-bottom:0; }}
    .app-sub {{ color:{SUBTEXT}; margin-top:-4px; }}
    .section-card {{ background:{CARD_BG}; border:1px solid {CARD_BORDER}; border-radius:10px;
                      padding:14px 18px; margin-bottom:12px; color:{TEXT}; }}
    .section-title {{ font-size:.85rem; font-weight:700; color:{PRIMARY};
                       text-transform:uppercase; letter-spacing:.04em; margin-bottom:6px; }}
    .rate-card {{ background:{RATE_BG}; border:1px solid {RATE_BORDER}; border-radius:10px;
                   padding:12px 16px; margin-bottom:12px; color:{TEXT}; }}
    </style>
    """,
    unsafe_allow_html=True,
)

MODEL = "openai/gpt-oss-120b"
MAX_HISTORY = 10
APP_URL = "https://matguide-ai.streamlit.app"  # update if your deployed URL differs

SECTIONS = [
    ("introduction", "Introduction"),
    ("composition", "Composition"),
    ("properties", "Properties"),
    ("purpose_use", "Purpose / Where It's Used"),
    ("types_grades", "Types / Grades"),
    ("standards", "Standard Specs / Codes"),
    ("precautions", "Site Precautions / Common Mistakes"),
    ("alternatives", "Alternatives / Substitutes"),
]

SYSTEM_PROMPT = (
    "You are a construction materials expert. Given a material name, "
    "produce a structured, accurate, practical guide for a civil "
    "engineer or site engineer. Use general engineering knowledge and "
    "widely-accepted ranges (e.g. typical compressive strength ranges), "
    "not invented precise numbers presented as certified test results. "
    "If the input is not a recognizable construction material, say so "
    "honestly instead of making something up. "
    "Respond ONLY with a valid JSON object with these exact keys: "
    "introduction, composition, properties, purpose_use, types_grades, "
    "standards, precautions, alternatives. Each value should be a short, "
    "clear paragraph or a few bullet-style sentences (as plain text, not "
    "nested JSON). No markdown code fences, no extra text outside the "
    "JSON object."
)

# ----------------------------------------------------------------------
# Reference rates (manually maintained — NOT a live feed).
# Source: Pakistan Bureau of Statistics inter-city CPI data, Jan 2026
# (via The News, Feb 2026). Edit these numbers whenever you have newer
# figures — there is no free real-time price API for this in Pakistan.
# ----------------------------------------------------------------------
RATES_LAST_UPDATED = "January 2026 (PBS city CPI data)"
RATES = {
    "cement": {
        "label": "Cement (OPC)", "unit": "per 50kg bag",
        "Lahore": 1467, "Karachi": 1391, "Islamabad": 1377,
    },
    "steel": {
        "label": "Steel / Rebar (Sariya)", "unit": "per ton",
        "Lahore": 212333, "Karachi": 211331, "Islamabad": 222583,
    },
    "bricks": {
        "label": "Bricks", "unit": "per 1000 bricks",
        "Lahore": 17463, "Karachi": 18000, "Islamabad": 24732,
    },
    "sand": {
        "label": "Sand (Rait)", "unit": "per truck",
        "Lahore": 7573, "Karachi": 6811, "Islamabad": 11773,
    },
    "bajri": {
        "label": "Bajri / Crush (Aggregate)", "unit": "per truck",
        "Lahore": 17463, "Karachi": 7854, "Islamabad": 14486,
    },
}
CITIES = ["Lahore", "Karachi", "Islamabad"]

RATE_KEYWORDS = {
    "cement": ["cement", "opc", "ppc", "portland"],
    "steel": ["steel", "tmt", "rebar", "sariya", "saria", "rod", "bar fe", "reinforcement bar"],
    "bricks": ["brick", "eent", "eint"],
    "sand": ["sand", "rait", "ret"],
    "bajri": ["bajri", "crush", "gravel", "aggregate", "gitti"],
}


def match_rate_key(material: str) -> str | None:
    m = material.lower()
    for key, words in RATE_KEYWORDS.items():
        if any(w in m for w in words):
            return key
    return None


# ----------------------------------------------------------------------
# Unit converter — pure math, no API needed.
# ----------------------------------------------------------------------
CONVERSIONS = {
    "Cubic Feet (Cft) → Cubic Meter (Cum)": lambda v: v / 35.3147,
    "Cubic Meter (Cum) → Cubic Feet (Cft)": lambda v: v * 35.3147,
    "Square Feet (Sft) → Square Meter (Sqm)": lambda v: v / 10.7639,
    "Square Meter (Sqm) → Square Feet (Sft)": lambda v: v * 10.7639,
    "Running Feet (Rft) → Meter": lambda v: v / 3.28084,
    "Meter → Running Feet (Rft)": lambda v: v * 3.28084,
    "Kilogram (Kg) → Ton": lambda v: v / 1000,
    "Ton → Kilogram (Kg)": lambda v: v * 1000,
    "Inch → Millimeter (mm)": lambda v: v * 25.4,
    "Millimeter (mm) → Inch": lambda v: v / 25.4,
}

# ----------------------------------------------------------------------
# Session state setup
# ----------------------------------------------------------------------
if "history" not in st.session_state:
    st.session_state.history = []          # list of {"material": str, "data": dict, "time": str}
if "favorites" not in st.session_state:
    st.session_state.favorites = {}        # material_lower -> {"material": str, "data": dict}
if "active_material" not in st.session_state:
    st.session_state.active_material = None
if "active_data" not in st.session_state:
    st.session_state.active_data = None
if "city" not in st.session_state:
    st.session_state.city = "Lahore"
if "compare_mode" not in st.session_state:
    st.session_state.compare_mode = False
if "compare_a" not in st.session_state:
    st.session_state.compare_a = None
if "compare_b" not in st.session_state:
    st.session_state.compare_b = None


def get_groq_key() -> str | None:
    key = st.session_state.get("manual_key")
    if key:
        return key
    try:
        key = st.secrets.get("GROQ_API_KEY")
    except Exception:  # noqa: BLE001
        key = None
    return key or os.environ.get("GROQ_API_KEY")


def query_material(material: str, api_key: str) -> dict:
    from groq import Groq
    client = Groq(api_key=api_key)
    resp = client.chat.completions.create(
        model=MODEL,
        max_tokens=1200,
        temperature=0.3,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Material: {material}"},
        ],
    )
    text = (resp.choices[0].message.content or "").strip()
    text = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start:end + 1]
    return json.loads(text)


@st.cache_data(show_spinner=False, ttl=86400)
def find_material_image(material: str, dark_mode: bool) -> str:
    """Look up a reference photo for the material via Wikipedia's free
    public API (no key needed). Falls back to a clean text placeholder
    (via placehold.co, also free/no key) if nothing is found, so a
    photo always renders and the material is always easy to identify —
    never raises, so a missed lookup never breaks the app."""
    candidates = [material, f"{material} (material)", f"{material} construction"]
    for name in candidates:
        try:
            url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + name.strip().replace(" ", "_")
            r = requests.get(url, timeout=6, headers={"User-Agent": "MatGuideAI/1.0"})
            if r.status_code == 200:
                thumb = r.json().get("thumbnail", {}).get("source")
                if thumb:
                    return thumb
        except Exception:  # noqa: BLE001
            continue
    label = quote_plus(material.strip()[:30] or "Material")
    bg = "4FA8E0" if dark_mode else "1F4E79"
    return f"https://placehold.co/600x360/{bg}/FFFFFF.png?text={label}&font=roboto"


def add_to_history(material: str, data: dict) -> None:
    st.session_state.history = [h for h in st.session_state.history if h["material"].lower() != material.lower()]
    st.session_state.history.insert(0, {"material": material, "data": data, "time": datetime.now().strftime("%H:%M")})
    st.session_state.history = st.session_state.history[:MAX_HISTORY]


def build_pdf(material: str, data: dict) -> bytes:
    from fpdf import FPDF

    def clean(txt: str) -> str:
        # fpdf2's core font only supports latin-1; swap anything else
        # out rather than crashing the PDF build.
        return (txt or "").encode("latin-1", errors="replace").decode("latin-1")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(31, 78, 121)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 10, clean(f"MatGuide AI - {material}"))
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 6, clean("AI-generated - verify against local specification/BOQ before use."))
    pdf.ln(4)

    for key, title in SECTIONS:
        content = (data.get(key) or "").strip()
        if not content:
            continue
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(31, 78, 121)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 8, clean(title.upper()))
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(20, 20, 20)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 6, clean(content))
        pdf.ln(3)

    out = pdf.output()
    return bytes(out)


def render_rate_card(material: str) -> None:
    """If the searched material matches a known rate category, show a
    reference-price card for the selected city."""
    rate_key = match_rate_key(material)
    if not rate_key:
        return
    info = RATES[rate_key]
    rate = info[st.session_state.city]

    st.markdown(
        f'<div class="rate-card">'
        f'<div class="section-title">📈 Reference Rate — {st.session_state.city}</div>'
        f'{info["label"]}: <b>PKR {rate:,}</b> {info["unit"]}'
        f'<div style="font-size:.75rem;color:{SUBTEXT};margin-top:4px;">'
        f'As of {RATES_LAST_UPDATED} — confirm with your local dealer before purchasing.</div>'
        f'</div>',
        unsafe_allow_html=True,
    )


def whatsapp_link(material: str, data: dict) -> str:
    intro = (data.get("introduction") or "")[:200]
    text = f"*{material}* — via MatGuide AI\n\n{intro}\n\nCheck the full guide: {APP_URL}"
    return f"https://wa.me/?text={quote(text)}"


def render_result(material: str, data: dict) -> None:
    st.write("")

    st.image(find_material_image(material, st.session_state.dark_mode), caption=material, use_container_width=True)

    render_rate_card(material)

    fav_key = material.lower()
    c1, c2, c3 = st.columns(3)
    with c1:
        if fav_key in st.session_state.favorites:
            if st.button("★ Unsave", use_container_width=True):
                del st.session_state.favorites[fav_key]
                st.rerun()
        else:
            if st.button("☆ Save", use_container_width=True):
                st.session_state.favorites[fav_key] = {"material": material, "data": data}
                st.rerun()
    with c2:
        st.download_button(
            "📥 PDF",
            data=build_pdf(material, data),
            file_name=f"{material.strip().replace(' ', '_')}_MatGuide.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
    with c3:
        st.link_button("💬 Share", whatsapp_link(material, data), use_container_width=True)

    st.write("")
    for key, title in SECTIONS:
        content = data.get(key, "").strip()
        if content:
            st.markdown(
                f'<div class="section-card"><div class="section-title">{title}</div>{content}</div>',
                unsafe_allow_html=True,
            )
    st.caption("AI-generated — verify grades, strengths, and codes against your local specification/BOQ before use.")


def render_compare_column(material: str, data: dict) -> None:
    st.image(find_material_image(material, st.session_state.dark_mode), caption=material, use_container_width=True)
    render_rate_card(material)
    for key, title in SECTIONS:
        content = data.get(key, "").strip()
        if content:
            st.markdown(
                f'<div class="section-card"><div class="section-title">{title}</div>{content}</div>',
                unsafe_allow_html=True,
            )


# ----------------------------------------------------------------------
# Sidebar
# ----------------------------------------------------------------------
st.sidebar.markdown("### Appearance")
st.session_state.dark_mode = st.sidebar.toggle("🌙 Dark Mode", value=st.session_state.dark_mode)

st.sidebar.divider()
st.sidebar.markdown("### Settings")
if not get_groq_key():
    st.sidebar.warning("No GROQ_API_KEY configured.")
    manual = st.sidebar.text_input("Paste a Groq API key to test now", type="password")
    if manual:
        st.session_state["manual_key"] = manual
        st.rerun()
    st.sidebar.caption("Get a free key at console.groq.com/keys. Kept in memory for this session only — not saved.")
else:
    st.sidebar.success("Groq API key detected.")

st.sidebar.divider()
st.sidebar.markdown("### 📐 Unit Converter")
conv_choice = st.sidebar.selectbox("Convert", list(CONVERSIONS.keys()))
conv_value = st.sidebar.number_input("Value", min_value=0.0, step=1.0, key="conv_value")
if conv_value:
    st.sidebar.success(f"= {CONVERSIONS[conv_choice](conv_value):,.4f}")

st.sidebar.divider()
st.sidebar.markdown("### 📈 Live Rates (Reference)")
st.session_state.city = st.sidebar.selectbox("City", CITIES, index=CITIES.index(st.session_state.city))
rate_rows = [
    {"Material": v["label"], "Rate (PKR)": f"{v[st.session_state.city]:,}", "Unit": v["unit"]}
    for v in RATES.values()
]
st.sidebar.dataframe(rate_rows, hide_index=True, use_container_width=True)
st.sidebar.caption(f"Manually-updated reference rates, not a live feed. Last updated: {RATES_LAST_UPDATED}. Confirm with your local dealer before purchasing.")

st.sidebar.divider()
st.sidebar.markdown("### 📜 Recent Searches")
if not st.session_state.history:
    st.sidebar.caption("Nothing searched yet this session.")
else:
    for h in st.session_state.history:
        if st.sidebar.button(f"{h['material']}  ·  {h['time']}", key=f"hist_{h['material']}", use_container_width=True):
            st.session_state.active_material = h["material"]
            st.session_state.active_data = h["data"]
            st.session_state.compare_mode = False
            st.rerun()

st.sidebar.divider()
st.sidebar.markdown("### ⭐ Favorites")
if not st.session_state.favorites:
    st.sidebar.caption("No favorites saved yet.")
else:
    for fav_key, fav in list(st.session_state.favorites.items()):
        fc1, fc2 = st.sidebar.columns([4, 1])
        if fc1.button(fav["material"], key=f"fav_{fav_key}", use_container_width=True):
            st.session_state.active_material = fav["material"]
            st.session_state.active_data = fav["data"]
            st.session_state.compare_mode = False
            st.rerun()
        if fc2.button("🗑", key=f"del_{fav_key}"):
            del st.session_state.favorites[fav_key]
            st.rerun()

st.sidebar.caption("History & favorites are kept for this browser session only — they reset if you refresh the page.")

# ----------------------------------------------------------------------
# Main UI
# ----------------------------------------------------------------------
st.markdown('<div class="app-header">🧱 MatGuide AI</div>', unsafe_allow_html=True)
st.markdown('<div class="app-sub">Construction Material Guide Assistant</div>', unsafe_allow_html=True)
st.write("")

st.session_state.compare_mode = st.toggle("🔍 Compare Two Materials", value=st.session_state.compare_mode)

if not get_groq_key():
    api_key_ready = False
else:
    api_key_ready = True

if st.session_state.compare_mode:
    cc1, cc2 = st.columns(2)
    with cc1:
        mat_a = st.text_input("Material A", placeholder="e.g. OPC Cement")
    with cc2:
        mat_b = st.text_input("Material B", placeholder="e.g. PPC Cement")
    compare_go = st.button("Compare", type="primary", use_container_width=True)

    if compare_go:
        if not mat_a.strip() or not mat_b.strip():
            st.warning("Please enter both materials.")
        elif not api_key_ready:
            st.error("No Groq API key configured. Add one in the sidebar or in Settings → Secrets.")
        else:
            with st.spinner(f"Comparing {mat_a} vs {mat_b}..."):
                try:
                    data_a = query_material(mat_a.strip(), get_groq_key())
                    data_b = query_material(mat_b.strip(), get_groq_key())
                    st.session_state.compare_a = {"material": mat_a.strip(), "data": data_a}
                    st.session_state.compare_b = {"material": mat_b.strip(), "data": data_b}
                    add_to_history(mat_a.strip(), data_a)
                    add_to_history(mat_b.strip(), data_b)
                except json.JSONDecodeError:
                    st.error("The AI response wasn't in the expected format. Please try again.")
                except Exception as e:  # noqa: BLE001
                    st.error(f"Could not generate the comparison: {e}")

    if st.session_state.compare_a and st.session_state.compare_b:
        st.write("")
        col_a, col_b = st.columns(2)
        with col_a:
            render_compare_column(st.session_state.compare_a["material"], st.session_state.compare_a["data"])
        with col_b:
            render_compare_column(st.session_state.compare_b["material"], st.session_state.compare_b["data"])
        st.caption("AI-generated — verify grades, strengths, and codes against your local specification/BOQ before use.")

else:
    material = st.text_input("Enter a construction material", placeholder="e.g. TMT Bar, M-Sand, PCC, AAC Block, HDPE Pipe")
    go = st.button("Get Guide", type="primary", use_container_width=True)

    if go:
        if not material.strip():
            st.warning("Please enter a material name.")
        elif not api_key_ready:
            st.error("No Groq API key configured. Add one in the sidebar or in Settings → Secrets.")
        else:
            with st.spinner(f"Looking up {material}..."):
                try:
                    data = query_material(material.strip(), get_groq_key())
                    add_to_history(material.strip(), data)
                    st.session_state.active_material = material.strip()
                    st.session_state.active_data = data
                except json.JSONDecodeError:
                    st.error("The AI response wasn't in the expected format. Please try again.")
                    st.session_state.active_data = None
                except Exception as e:  # noqa: BLE001
                    st.error(f"Could not generate the guide: {e}")
                    st.session_state.active_data = None

    if st.session_state.active_data:
        render_result(st.session_state.active_material, st.session_state.active_data)

st.write("")
st.caption("MatGuide AI · Powered by Groq")
