"""
MatGuide AI — Construction Material Guide Assistant
------------------------------------------------------
Type any construction material name and get a structured guide:
introduction, composition, properties, purpose/use, types/grades,
standards, precautions, and alternatives — generated by an LLM
through the Groq API.

Run:
    streamlit run app.py

API key:
    Set GROQ_API_KEY in .streamlit/secrets.toml (see
    .streamlit/secrets.toml.example) or as an environment variable.
    You can also paste a key directly in the sidebar for a quick local
    test — it is only kept in memory for this session, never saved
    to disk or committed anywhere.
"""

from __future__ import annotations

import json
import os
import re

import streamlit as st

# ----------------------------------------------------------------------
# Page config & styling
# ----------------------------------------------------------------------
st.set_page_config(page_title="MatGuide AI", page_icon="🧱", layout="centered")

PRIMARY = "#1F4E79"
st.markdown(
    f"""
    <style>
    .app-header {{ font-size:1.8rem; font-weight:800; color:{PRIMARY}; margin-bottom:0; }}
    .app-sub {{ color:#6B7280; margin-top:-4px; }}
    .section-card {{ background:#FFFFFF; border:1px solid #E5E7EB; border-radius:10px;
                      padding:14px 18px; margin-bottom:12px; }}
    .section-title {{ font-size:.85rem; font-weight:700; color:{PRIMARY};
                       text-transform:uppercase; letter-spacing:.04em; margin-bottom:6px; }}
    </style>
    """,
    unsafe_allow_html=True,
)

MODEL = "openai/gpt-oss-120b"

SECTIONS = [
    ("introduction", "Introduction"),
    ("composition", "Composition"),
    ("properties", "Properties"),
    ("purpose_use", "Purpose / Where It's Used"),
    ("types_grades", "Types / Grades"),
    ("standards", "Standard Specs / Codes"),
    ("precautions", "Site Precautions / Common Mistakes"),
    ("alternatives", "Alternatives / Substitutes"),
]

SYSTEM_PROMPT = (
    "You are a construction materials expert. Given a material name, "
    "produce a structured, accurate, practical guide for a civil "
    "engineer or site engineer. Use general engineering knowledge and "
    "widely-accepted ranges (e.g. typical compressive strength ranges), "
    "not invented precise numbers presented as certified test results. "
    "If the input is not a recognizable construction material, say so "
    "honestly instead of making something up. "
    "Respond ONLY with a valid JSON object with these exact keys: "
    "introduction, composition, properties, purpose_use, types_grades, "
    "standards, precautions, alternatives. Each value should be a short, "
    "clear paragraph or a few bullet-style sentences (as plain text, not "
    "nested JSON). No markdown code fences, no extra text outside the "
    "JSON object."
)


def get_groq_key() -> str | None:
    key = st.session_state.get("manual_key")
    if key:
        return key
    try:
        key = st.secrets.get("GROQ_API_KEY")
    except Exception:  # noqa: BLE001
        key = None
    return key or os.environ.get("GROQ_API_KEY")


def query_material(material: str, api_key: str) -> dict:
    from groq import Groq
    client = Groq(api_key=api_key)
    resp = client.chat.completions.create(
        model=MODEL,
        max_tokens=1200,
        temperature=0.3,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Material: {material}"},
        ],
    )
    text = (resp.choices[0].message.content or "").strip()
    text = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    return json.loads(text)


# ----------------------------------------------------------------------
# Sidebar
# ----------------------------------------------------------------------
st.sidebar.markdown("### Settings")
if not get_groq_key():
    st.sidebar.warning("No GROQ_API_KEY configured.")
    manual = st.sidebar.text_input("Paste a Groq API key to test now", type="password")
    if manual:
        st.session_state["manual_key"] = manual
        st.rerun()
    st.sidebar.caption("Get a free key at console.groq.com/keys. Kept in memory for this session only — not saved.")
else:
    st.sidebar.success("Groq API key detected.")

# ----------------------------------------------------------------------
# Main UI
# ----------------------------------------------------------------------
st.markdown('<div class="app-header">🧱 MatGuide AI</div>', unsafe_allow_html=True)
st.markdown('<div class="app-sub">Construction Material Guide Assistant</div>', unsafe_allow_html=True)
st.write("")

material = st.text_input("Enter a construction material", placeholder="e.g. TMT Bar, M-Sand, PCC, AAC Block, HDPE Pipe")
go = st.button("Get Guide", type="primary", use_container_width=True)

if go:
    if not material.strip():
        st.warning("Please enter a material name.")
    elif not get_groq_key():
        st.error("No Groq API key configured. Add one in the sidebar or in Settings → Secrets.")
    else:
        with st.spinner(f"Looking up {material}..."):
            try:
                data = query_material(material.strip(), get_groq_key())
                st.write("")
                for key, title in SECTIONS:
                    content = data.get(key, "").strip()
                    if content:
                        st.markdown(
                            f'<div class="section-card"><div class="section-title">{title}</div>{content}</div>',
                            unsafe_allow_html=True,
                        )
                st.caption("AI-generated — verify grades, strengths, and codes against your local specification/BOQ before use.")
            except json.JSONDecodeError:
                st.error("The AI response wasn't in the expected format. Please try again.")
            except Exception as e:  # noqa: BLE001
                st.error(f"Could not generate the guide: {e}")

st.write("")
st.caption("MatGuide AI · Powered by Groq")
